# Generated by Django 4.2.3 on 2023-08-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_department_role_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='profile/'),
        ),
    ]
