# Generated by Django 4.2.3 on 2023-08-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_employee_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_img',
            field=models.FileField(default='profile/anonymous.jpg', max_length=250, upload_to='profile/'),
        ),
    ]
